sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - pypi
install:
- pip install python-coveralls
script:
- coverage run test.py
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: sih4sing5hong5
  password:
    secure: rDNaLrcb00fNYmkYV1ANG9Ts0MRvyMNFWlqEu2LY7bMJbTEm24t8Yn+eU1AC86eEZdouknWaEBWKsdc1fVjtz4oQS75dfsRHY32P6T/dijRs7BKSboy624+rdOikOVTHQL4jEXALQQwqDMTN1+Bs5lKouho63prHnChc0u1v3bHmKCQClP44j6sK9jfP4tdKXPW6VvjNEWWCX5EEpVwGltC6MsXLjo/PNkNiYB+rtb/INOryRH3nfLIRBVoGovdlBMBr0KWPruOUzzGoWL8v0aQuSba89/kdawwDcjpxrqERz2AveG5ltzrQVEgEkoTdJR1fPlN3TS5ZTlnmpQK76zmyE2sKM92pZGuHH+IAdLYMUJlAtTEixr+WemdzX6D0wWyzO2p48Xag+5tK7Z1FmI4oHlXqYcfpYr4O1tbMeMOfU74eufjkgxcoyf55Kg7TcqJM94BgsHB9sqh29SdhxJ0DAGxZzI+RD8l50fkGV139GsxsoNohTPxamhhBTH0QS0NkKsLbpAbn7qJuK6DPt/prtUCDMJIKzG5ttszRwkGV3FpV9rCxGlqZvqhJX5SIYSNRZvOaw2D7mW5U4Ayjq8Twfs54Zi/YjlAJjT01LcCzM5V7Umi0vCcgQBJVuNIPsX9Nm5UApFIh5oJkPt7mSch/lZxZKZzS/R55vWBO9IE=
  on:
    repo: sih4sing5hong5/libavwrapper
    branch: pypi
